### ISSUE TITLE
After running script and reboot get dotnet: cannot execute: required file not found

### ISSUE THREAD

**Issue by johnkattenhorn** [pjgpetecodes/dotnet8pi#6]
I'm pretty sure I've followed the excellent blog instructions faithfully on a new Raspberry Pi 5.

All latest patches and updates are applied

Logged on User is pi5 (maybe I should have used default pi here?)

`dotnet --info` throws:

`bash: /usr/local/bin/dotnet: cannot execute: required file not found`

Any ideas ?

**Comment by pjgpetecodes** [comment]
I'll have a look in the new year if that OK... See what's occurring... Just to check, this is Raspberry Pi OS yeah?

**Comment by johnkattenhorn** [comment]
Yep confirmed - Raspberry Pi OS – SD Card came with the PI5 with the OS pre-installed.

Thanks Peter

**Comment by johnkattenhorn** [comment]
Just more info which might be useful, if I run

`uname -m` - it returns `aarch64` which makes sense since this is a raspberry pi 5

if I run `getconf LONG_BIT` it returns `32` which I think means I'm running 32bit version of Raspberry OS.

`cat /etc/os-release` returns `VERSION_ID="12"`

**Comment by pjgpetecodes** [comment]
Thanks for all the info... Super useful!

Worth noting that GPIO was borked on the Pi 5 (aside from simple on off stuff).

I'll have a look when I get back to the office and let you know!

**Comment by johnkattenhorn** [comment]
Yeah I saw that from the issue tracker you posted - I'll keep an eye, it's a shame.

I'm interested in support for sleep mode and might try to contribute this if it's not already supported.

**Comment by pjgpetecodes** [comment]
Can you try this version @johnkattenhorn?

```
wget -O - https://raw.githubusercontent.com/pjgpetecodes/dotnet8pi/jonathan/install.sh | sudo bash
```

**Comment by johnkattenhorn** [comment]
I ran this command @pjgpetecodes, and seemed to go to plan but the result is the same - still produces the error `required file not found`

**Comment by pjgpetecodes** [comment]
*EDIT:

Ignore all of the below and see my latest comment... Leaving this here for reference...

---

Annoyingly, I've just burned a brand new Bookworm image on a Pi 4 and tried it, and the original command zooms straight through on my card and works first time... 

Can you run the following command;

`cat /etc/os-release`

I get;

> petecodes@raspberrypi:~ $ cat /etc/os-release
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"

And also;

`uname -a`

I get;

> petecodes@raspberrypi:/opt/dotnet/sdk/8.0.100 $ uname -a
> Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

and 

`uname -m`

I get;

> petecodes@raspberrypi:~ $ uname -m
> aarch64

Then perhaps, assuming you have time... Can you try reimaging using the latest Raspberry Pi imager (This is what I've just done)... 

https://www.raspberrypi.com/software/

And try the original command again;

`wget -O - https://raw.githubusercontent.com/pjgpetecodes/dotnet8pi/main/install.sh | sudo bash`...

Thanks in advance!

**Comment by pjgpetecodes** [comment]
Ok... Ignore all of the above @johnkattenhorn ... 

Seems that Raspberry Pi OS is likely giving the wrong answer to which arch of OS is running once you've done an update and use `uname -m`!

`uname -m` I think is supposed to tell you the OS architecture and not the Processor Arch?

I've switched to using the same `getconf LONG_BIT` that you checked with to check for 32bit/64bit now...

Try removing the existing installation using;

`sudo rm -rf /opt/dotnet`

Then try running the main command again;

`wget -O - https://raw.githubusercontent.com/pjgpetecodes/dotnet8pi/main/install.sh | sudo bash`

With all of that said tho... If you're using a Pi 5... You really should be using the latest 64 bit bookworm release anyway... So, I recommend reimaging like I said in the previous comment above!

**Comment by johnkattenhorn** [comment]
Hey @pjgpetecodes - success! That worked.

100% agree with the 64bit point though so I'll do that - I'm not sure why they shipped the SD with the 32bit version of the OS.

Thanks for working with me on this one - much appreciated!

**Comment by pjgpetecodes** [comment]
Wahoo! Mega! So glad we got you up and running!
